blurry-dev/blurry

- blurry/__init__.py
- blurry/settings.py
- docs/blurry.toml
- docs/content/templates/syntax.md
Adds support for non-Schema.org type template names using the template_schema_types setting.
Also adds small improvements to some edited files.
> feat: support non-schema type template names

- blurry/markdown/__init__.py
- blurry/utils.py
- noxfile.py
- tests/test_utils.py
Fixes relative path handling in Markdown files, which wasn't always working correctly and relied on some relative path trickery. Paths are now calculated with the source file path taken into consideration
Closes #20
> fix: relative path handling in Markdown files

- docs/content/templates/examples.md
A tiny fix that may help your users getting started
> Fix typo in documentation so the example actually works

- blurry/markdown/__init__.py
Removes pathname from front matter since it is not a Schema property
Closes #30
> fix: remove pathname from front matter

- blurry/markdown/front_matter.py
When working with templates one makes errors in the syntax. Currently, there is no log of the details, while the toml parser does print out the location (and nature) of the error.
I restructured the code so it does print the message of an exception.
I restrained from refactoring this code further to be able to also print the file path because it would have destroyed the message from where this code was adapted.
> Print front-matter errors when reading a template

- blurry/__init__.py
- blurry/constants.py
- blurry/settings.py
Adds a setting to customize the Jinja template extension used for schemas referenced in Markdown front matter.
For example, now template can have an extension of ".jinja.html" rather than ".html" for better editor support.
> feat: setting for Markdown file Jinja extension

- blurry/__init__.py
Copies global values in Jinja context so they aren't modified in Jinja template variable operations, like sorted()
> refactor: copy global values in Jinja context

- blurry/__init__.py
- blurry/cli.py
This PR adds a stylized "blurry" at the top of the CLI output for recognition, adds plugins in a table rather than printing lists, and updates the line about gathered tasks to mention Markdown files specifically. I'll likely put up a follow-up PR to add an image processing progress bar, which will be helpful because image processing happens in the background.
Before:
```
Markdown plugins:
['container', 'punctuation', 'python_code', 'python_code_in_list']
HTML plugins:
['minify_html']
Jinja filter plugins:
[]
Gathered 21 tasks
Built site in 0.102329 seconds
```
After:
```
.  .             
|-.| . ..-..-.. .
`-''-'-''  '  '-|
`-'
┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Markdown Plugins    ┃ HTML Plugins ┃ Jinja Plugins ┃ …
```
> Add stylized 'blurry' and plugin table to CLI output

- blurry/markdown/__init__.py
- docs/content/templates/syntax.md
Handles image schema property in Markdown front matter properly if it is an object
Closes #47
See this page with a working image object with a `contentUrl`: https://65e4b865d2776bb58dfb3e11--blurry-docs.netlify.app/templates/syntax/
> fix: handle image property as string or dict

- blurry/markdown/__init__.py
- pyproject.toml
This avoids a syntax error in the HTML
> #66 Add a type attribute to the source tag for Avif images.

- blurry/markdown/__init__.py
- blurry/utils.py
- docs/content/content/images.md
- tests/test_utils.py
This code caused an issue with the HTML output and is better suited to a plugin.
Fixes #40, albeit aggressively
> Axe code that removes lazy loading from 1st image

- blurry/markdown/__init__.py
- docs/content/templates/context.md
Removes global thumbnailUrl computed front matter value because not every schema type has this property
> fix: remove global thumbnailUrl

- blurry/__init__.py
Moves blurry name and plugin printing to the build command so they aren't printed when code is imported or when blurry is run without a command
> fix: blurry name and plugins printing on import

- blurry/__init__.py
- blurry/templates.py
- docs/content/content/dynamic.md
- docs/content/getting-started/quick-start.md
- docs/pyproject.toml
- docs/templates/base.html.jinja
Processes files ending in .jinja in the content folder, stripping the
.jinja extension.
This is useful for generating dynamic files, like RSS feeds
Closes #44
> 44 process jinja files in content dir

- blurry/__init__.py
- blurry/images.py
- blurry/sitemap.py
Improves performance by:
- Copying non-Markdown file to build directory only if it doesn't exist
- Uses a ThreadPoolExecutor rather than asyncio in some places
- Starts processing files as soon as they're found during the build rather than gathering them all first
- Building only relevant Markdown/Jinja files on file change in runserver rather than triggering an entire build
Also adds transient progress bars to show build progress
> refactor: improve performance, add progress bars

- blurry/markdown/__init__.py
- blurry/plugins/jinja_plugins/blurry_image_extension.py
- docs/content/content/images.md
From the W3 validator:
Trailing slash on void elements has no effect and interacts badly with unquoted attribute values.
> fix: remove trailing slash on <img>

- README.md
Adds a badge showing downloads/month and a note that minor versions before v1.0.0 may not be backwards compatible
> readme: add downloads and compatibility note

- .github/workflows/deploy.yml
Deploys the docs site on release rather than on merge into main so docs don't get ahead of the latest published package
> refactor: deploy docs site on release

- blurry/markdown/__init__.py
- blurry/plugins/jinja_plugins/filters.py
- pyproject.toml
- tests/test_jinja_filter_plugins.py
- tests/test_markdown_renderer.py
Adds headings and url_path Jinja filter plugins and updates Markdown heading handling to add an ID to the headings.
These filters enable creating a table of contents and simplify showing whether a link is active for the current page.
> feat: headings and url_path Jinja filters

- docs/content/plugins/intro.md
- docs/poetry.lock
- docs/pyproject.toml
Removes that plugin because it interferes with heading IDs. It may be worth refactoring the plugin as an HTML plugin instead.
> chore: remove blurry-plugin-blur-blurry-name

- blurry/__init__.py
- blurry/file_processors/__init__.py
- blurry/gather_file_data_by_directory.py
- blurry/runserver_handlers.py
- blurry/utils.py
- tests/test_utils.py
Tidies the top-level `__init__.py` by moving functions into logical subdirectories
Also closes #111 in the process
> refactor: move functions out of top init file

- blurry/commands/clean.py
- docs/content/commands/build.md
- docs/content/commands/clean.md
- docs/content/commands/init.md
- docs/content/commands/runserver.md
Tweak the CLI command docs to move the command name into code blocks in some cases and to add TOC entries.
Also adds a broom emoji to the clean command output for fun.
> docs: update CLI command docs

- blurry/file_processors/__init__.py
- blurry/schema_validation.py
- tests/test_schema_validation.py
Tidies schema validation by renaming some variables and removing an unnecessary loop
> refactor: tidy schema valdation

- docs/templates/assets/docs.css
Fixes the spacing of the TOC in docs pages when the TOC appears above the page content (small-medium screens).
Before:
After:
> fix: TOC spacing in docs when above content

- .github/workflows/publish.yml
Updated `.github/workflows/publish.yml` to remove the deprecated `--sync` flag from `poetry install`. The recommended approach is to use `poetry sync` instead.
> Fix workflow – removed deprecated `--sync` from `poetry install`

- blurry/__init__.py
- blurry/cli.py
- blurry/images.py
- blurry/settings.py
- docs/content/content/images.md
Adds a WEBP fallback if the local system can't encode images as AVIF.
Adds a message to the CLI and updates the docs accordingly
Closes #195 
Example CLI message:
```
.  .             
|-.| . ..-..-.. .
`-''-'-''  '  '-|
`-'
┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Markdown Plugins    ┃ HTML Plugins ┃ Jinja Plugins ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ container           │ minify_html  │ body_to_cards │
│ punctuation         │              │ headings      │
│ python_code         │              │ url_path      │
│ python_code_in_list │              │ blurry_image  │
└─────────────────────┴──────────────┴───────────────┘
AVIF support not found. Falling back to WEBP. See https://trac.ffmpeg.org/wiki/Encode/AV1
[I 250613 16:16:11 server:331] Serving on …
```
> feat: fallback to WEBP if AVIF no available
